### ISSUE TITLE
Error Writing scoop: 0

### ISSUE THREAD

**Issue by jimenezfer** [JohnnyFFM/Poc1to2Converter#12]
![blas](https://user-images.githubusercontent.com/23113643/41444742-302e65bc-7002-11e8-831b-8cf0d7bbbcb0.PNG)

**Comment by JohnnyFFM** [comment]
Hi, the converter is not able to write to your file. Was there an error popup? The good news: your file is unchanged, so no damage, you can just try again. 

It might be the case that direct I/O fails. You can disable direct i/o by starting the converter with the command line flag -ddio.

**Comment by jimenezfer** [comment]
I do have an orico 10 port device in between the drives and the pc(sometimes it craps out),  none of my plot files starts with a scoop 0, for a moment I though that was the problem. There was a pop up yes. Am gonna try again. 

Thanks!

**Comment by jimenezfer** [comment]
![doma](https://user-images.githubusercontent.com/23113643/41475160-3ab622f8-707b-11e8-9e49-2afc96724678.PNG)

**Comment by jimenezfer** [comment]
This errors happens when running with the flag.

**Comment by JohnnyFFM** [comment]
Hi, I just googled the „semaphore timeout period has expired“ error message and there is plenty of hits on it. Seems like it can happen with external USB enclosures and could be driver and/or hardware related. My suspect is the Orico thing in between, did you try a direct connect?

**Comment by jimenezfer** [comment]
Indeed , my apologies. Its moving forward bypassing the orico multiport thingy. Thanks! 
Have a good one.
