### ISSUE TITLE
Poc1to2Converter v.2.3 - is it processing plots files correctly?

### ISSUE THREAD

**Issue by Shekelme** [JohnnyFFM/Poc1to2Converter#13]
I have converted my plots files with Poc1to2Converter v.2.3 on 2 different PCs. blagominer-v1.170911_AVX says about "REALLY BAD deadlines" on both these PCs. Is this something that I should worry about?

Judging by the numbers of nonces the problem is related to different plot files on different disks.

![reallybaddeadlines](https://user-images.githubusercontent.com/26449500/41498835-23f43240-71a1-11e8-91e3-cade32024488.JPG)

**Comment by JohnnyFFM** [comment]
Hi, has your Pool moved to PoC2? My converter should be working fine 😉

**Comment by JohnnyFFM** [comment]
Closing this. Converter has passed all tests. Your issue might be pool related. No further input so far, no other users complaining.
