### ISSUE TITLE
Disparity in time to convert for same plot file size on same drive

### ISSUE THREAD

**Issue by mwicherski** [JohnnyFFM/Poc1to2Converter#17]
During my conversions, on the same drives, plots of differing sizes take different amounts of time to complete, to the tune of 8 hrs vs 23 hrs. This screenshot shows 16 vs 21.

![image](https://user-images.githubusercontent.com/2329790/41704893-509cef8c-74ec-11e8-8464-f309d93954f6.png)

**Comment by JohnnyFFM** [comment]
Hi, 

Yes, this is nothing unusual and there is nothing I can do about it. Harddisk speed is not constant, it will depend on the physical location of the data. SMR drives are more effected than PMR. There is faster areas and slower areas on a hard drive. The time remaining is only an estimate based on elapsed time and processed data. You might have a more constant speed if you use the speed boost option (if you can sacrifice more ram).

Best, 

Johnny

**Comment by mwicherski** [comment]
Thanks for the quick reply. I was hoping that maybe it was doing an integrity check and fixing corrupt plots it may have found :)

In any case, thank you.
