### ISSUE TITLE
Resume in-place conversion when it gets interrupted

### ISSUE THREAD

**Issue by systemofapwne** [JohnnyFFM/Poc1to2Converter#2]
My miner unfortunately suffered from a power outage last night, corrupting 6 TB of plots while converting POC1 -> 2 was currently in progress midway.
To my understanding how conversion works, wouldn't it be sufficient to mark the current scoop (or block of scoops) as nCurrent somewhere on any disk (or the disk in progress to get converted) so whenever conversion fails, it can simply start conversion from the next scoop/block of scoops? With that, one can continue the conversion process and only two scoops or block of scoops are corrupted and not "almost a whole plotfile".

**Comment by JohnnyFFM** [comment]
Hi! 

I'm very sorry to hear that, a power outage during conversion is the worst case scenario. 

Currently a resume feature is not implemented. If a scoop gets damaged, a perfect repair would have the same computational effort as re-plotting the whole file. An alternative would be to ignore the damaged scoop and continue with the next scoop as per your suggestion. Your plotfile's healthiness would still be ~99.95%. Also there is a good chance that the outage happened during the reading in which case the conversion could resume without any error. 

Here's what I'm going to do: I will implement a log-file, logging the scoop progress and start and stop of each read & write operation. Additionally I'm going to implement a command-line switch allowing for a  start at a specific scoop. This way a skilled user would be able to assess the status of his damaged plotfile and resume the conversion.

Best, 
Johnny

**Comment by JohnnyFFM** [comment]
Hi, next version 2.0 will have a logging feature and a command line switch 
-startscoop   //skip scoops - for repair attempts [0..2047]
