### ISSUE TITLE
Add Command Line Paramter

### ISSUE THREAD

**Issue by Ranman86** [JohnnyFFM/Poc1to2Converter#3]
Would be nice to add command line arguments to start the progress from a batch file.

**Comment by JohnnyFFM** [comment]
Hi Ranman, 

The bad news: Currently no plans for a command line version of the converter at the moment, You can already batch several files in the gui. Those files will be processed sequentially. For multiple drives or parallel conversion, just use multiple instances of the app. Why would you prefer a command line? Too many drives :) ?

The good news: I do feature a command line tool called plotmerge, can also be found in my repo. If you "merge" a file such that source and target file have the same amount of nonces it is equivalent to converting disk-to-disk. (e.g. plotmerge ID_0_20000_20000 ID_0_20000). But not working inplace. 

Best, Johnny

**Comment by JohnnyFFM** [comment]
Hi, 
just did a commit adding command line options. Will be included in the 2.0 expected on weekend!
Options:
-autostart      //autostart conversion
-srcfile file     //add a single file
-srcdir dir      //add a directory
-tardir dir      //specify target for disk-to-disk
-startscoop   //skip scoops - for repair attempts
-ddio            //disable direct I/O for compatibility
-mem 1024  //specify memory to be used in MB (min 96 max 4096)
