### ISSUE TITLE
Large Plotfile Failure

### ISSUE THREAD

**Issue by nvOC-Stubo** [JohnnyFFM/Poc1to2Converter#6]
I have 513 TB of plot files, most of which are 14.5 TB plots made by striping 2 8TB disks on my LSI Raid controllers. When I try to run Poc1Poc2Conv.exe on these files, a second after I click Start Conversion, the program just exits. I have a 1 7.27 TB plot that Poc1Poc2Conv.exe seems to be working fine on.

Is there problem supporting > 8 TB plot files?

**Comment by JohnnyFFM** [comment]
Hi, I’m looking into this. Have 2 questions:
A) What version did you use?
B) What MemLimit did you use?
Best, Johnny

**Comment by nvOC-Stubo** [comment]
I am using v.1.9 Pre-Release and the max memory - 4096 Mb.

**Comment by JohnnyFFM** [comment]
Can you try to lower the memlimit and let me know what happens? If not working, can you try stable 1.8?

**Comment by nvOC-Stubo** [comment]
I just tried the 3G and 2G memory limits with beta 1.9 and get the same behavior - it just exits after a second or so. I also tried 1.8 at 4G and 2G memory limit and get the same.

**Comment by JohnnyFFM** [comment]
Ok thanks for testing. I will try to reproduce this on my side. I assume
you‘ve tried inplace conversion. Could you share your starting nonce and the number of nonces of your plotfile, going to produce a similar file on my machine.

**Comment by nvOC-Stubo** [comment]
Sure. I actually tried 2 different plotfiles with different starting nonces but the same # of nonces.
sn: 3700000001
n:  61039000

If it matters, I used the latest version of Blago's XPlotter_avx2.exe for plotting.

**Comment by JohnnyFFM** [comment]
I, was not able to replicate the bug yet. I've added some error handling to 1.8 --> 1.8b. Could you please test and let me know the error message if any. Thanks, Johnny
[Poc1Poc2Conv.v.1.8b.compiled.zip](https://github.com/JohnnyFFM/Poc1to2Converter/files/2070968/Poc1Poc2Conv.v.1.8b.compiled.zip)

**Comment by nvOC-Stubo** [comment]
Using 1.8b, I get:
**I/O Error - Read**
Scoop: 0 Handle does not support synchronous operations. The parameters to the FileStream constructor may need to be changed to indicate that the handle was opened asynchronously (that is, it was opened explicitly for overlapped I/O).

Additional update: I believe the issue is with compatibility between the disk driver (LSI Megaraid) in my system and the code being used by this utility. I say that because I realized that the conversion that I was doing on my 8 TB plot was running really slowly. After 6 hours, it had processed 34 of 2048 and was predicted to take 12 days to complete. So, I found your modified version of Xplotter (supports PoC2) and began replotting that drive using it and that process seems to be running at same speed as did the original Xplotter (with the -poc2 switch). That leads me to believe that the issue may be with the code used in the converter (C#) versus the plotter (C, assembly).

Obviously, I would prefer to convert rather than replot but at least I have a viable path forward in the form of your modified Xplotter, so I am not throwing in the towel and replotting just yet as that will take a few weeks with my 34 16 Tb plots.

Thanks for all of your great work in supporting Poc2.

**Comment by JohnnyFFM** [comment]
One last test: What happens if you go back to version 1.6 **and** use less than 4096MB ram (e.g. 4000MB). v.1.6 doesn't use low level I/O and might mitigate this issue.

**Comment by nvOC-Stubo** [comment]
Ok. 1.6 seems to run with memory set to 4000 Mb. It is currently saying 1 day, 15 hours for the conversion of this 16 Tb plot (6/2048 after 5 mins). I suspect that time may slip but so far so good as long as it is less than the ~40 hours that it takes to replot altogether. 

Do you have any plans to write a version of the converter that uses the same very low level commands that the Xplotter uses? That would seem to be ideal for my situation given what we know so far.

**Comment by JohnnyFFM** [comment]
40ish hours for 16tb is a good speed. It will not get better. But! You can convert several drives at the same time as it is just I/O, but you most likely cant plot several drives at the same time. (I‘ve converted 10disks in parallel, no issues). Regarding the issue with direct i/o: I think i know what it is and will create a new version to fix this.

**Comment by nvOC-Stubo** [comment]
40 hours is decent - it is up to about 41 hours now. That is almost exactly the same as the original plot speed using Xplotter which makes sense because 99% of the time doing that in my case was in writing out the scoops. With the conversion (as opposed to replotting), I can run much more parallel due to lower memory requirements and use very little CPU so that is a substantial advantage.

Let me know when you get a new version ready and I will happy to test it and provide feedback since I have so many large plots to convert.

Thanks again for you assistance and keep up the great work.

**Comment by JohnnyFFM** [comment]
Hi, was able to reproduce the error and should have found a fix,. 
[Poc1Poc2Conv.v.1.8b.compiled.zip](https://github.com/JohnnyFFM/Poc1to2Converter/files/2072255/Poc1Poc2Conv.v.1.8b.compiled.zip)
[Poc1Poc2Conv.v.1.9b.compiled.zip](https://github.com/JohnnyFFM/Poc1to2Converter/files/2072256/Poc1Poc2Conv.v.1.9b.compiled.zip)

Please let me know if this is working for you. Was the same fix for 1.8 and 1.9, so if one of the 2 is working, both are working, 

Cheers, Johnny

**Comment by nvOC-Stubo** [comment]
Before I dive in and risk either bricking one of my plots or it being slower than 1.6, I must ask, is you expectation that this will be faster than 1.6 with the fix?

BTW, 1.6 is still moving along nicely at 143/2048 so I estimate the total time at 41 hours for a 16 Tb plot.

**Comment by nvOC-Stubo** [comment]
I just got some feedback from a friend who is also converting his plots. He is using 1.9 and he tells me that it is taking him 36 hours to do a 8 TB drive. Since I appear to be cable of doing 16 TB in 41 hours with 1.6, that tells me that something in the combination of my RAID controller, write caching and the RAID 0 (striped) volume are helping quite a bit over JBOD. 

I wanted to get this information to you to help answer the question above about your performance expectations for the fix. In other words, if you are forcing a write through, it may actually hurt my performance.

**Comment by JohnnyFFM** [comment]
Well, my expectation is that it is faster than 1.6 (my perf on sas was terrible without that). What I could do: I could compile a dummy version without the shuffle feature. You could use that to safely test performance of a inplace conversíon. You could safely abort it as it reads and writes the same data (basically doesn't change the plot file). Would that be of interest?

Regarding Raid: Yes, no surprise, it has to outperform JBOD, especially when converting. I think there is also a positive effect on CPU usage when reading a lot of drives . But, if a single drive fails, you lose two drives of capacity. I've tested a lot of 8GB drives, typical speed was 32h for PMR and 48h for SMR.

**Comment by JohnnyFFM** [comment]
Here a Benchmark only version for testing. 
[Poc1Poc2Conv.v.1.8b.BENCHMARKONLY.compiled.zip](https://github.com/JohnnyFFM/Poc1to2Converter/files/2072585/Poc1Poc2Conv.v.1.8b.BENCHMARKONLY.compiled.zip)

**Comment by nvOC-Stubo** [comment]
Yes, that would absolutely be of interest. I would have no qualms about running it for an hour or so to see what kind of performance to expect. It sounds like you would be reading the data, doing the conversion, but throwing away the converted data and writing original data back.

Funny you mention SAS because that is what I am running. I have 3 LSI cards that connect to SAS expanders. However, I am actually using SATA (8 TB WD) drives connected to those expanders. 

EDIT: I see you just posted the benchmark version so let me get back to you in about an hour with my impressions.

**Comment by nvOC-Stubo** [comment]
So, after about 1/2 hour, the benchmark version has an estimated total time of 37.75 hours versus about 40.4 hours with 1.6 for a 16 Tb plot conversion on my rig. Attached is a screenshot. Top is 1.8 Benchmark. So for me, 1.8 is about 10% faster than 1.6. While not huge, it should help to offset the effect of running a bunch of them in parallel.

![convperf](https://user-images.githubusercontent.com/34128039/40982818-38391d36-68ac-11e8-9d93-920afe11c940.JPG)

The good news is that the fix you made seems to work so thank you very much!

**Comment by JohnnyFFM** [comment]
Excellent, yes the 10% is what I was expecting! And yes, the bug is fixed :-). I'll close this now and have the 1.8b pushed to Qbundle. Many thanks for your help!

**Comment by nvOC-Stubo** [comment]
So, using 1.6, the conversion is going to complete in just over 36 hours which is better than expected:
![16convperf](https://user-images.githubusercontent.com/34128039/41066460-ded96fde-69af-11e8-89b6-c5e258621b8c.JPG)

I will follow up one more time (in a couple of days) to report on the performance of 1.81 on another 16 Tb plot.

**Comment by JohnnyFFM** [comment]
planning to have 2.0 catch the exception and automatically switch to buffered I/O.
