### ISSUE TITLE
IO Error: Seek to Read

### ISSUE THREAD

**Issue by DefiantMiner** [JohnnyFFM/Poc1to2Converter#9]
This error keeps coming up on several plot sets (different drives/controllers), all of which have been working flawlessly for a year or more.  Can't believe its HW related.

IO Error Seek to Read
Scoop: 4095 The parameter is incorrect

It seems to come up on the second or later plot on a drive and fails the convert session, all remaining plots on the drive come up with the same error if tried again.  The plots are not sequential on the individual drives - if that matters.  Only 1 out of 5 drives attempted has completed so far....not good.  Because the error fails all the other plots on the drive, I have no choice but to re-plot those from scratch.

I'm running Win10_1709, 32GB mem, i5, multiple single disks, running 2 instances of your converter and mining with latest JMiner (GPU based).  Performance monitor shows no bottlenecks other than the drives themselves.  Hardly using 5GB of RAM when running.  Drives being converted were removed from active mining path list.

Any ideas? 
![img_4726](https://user-images.githubusercontent.com/23225843/41159564-8cb313ce-6af2-11e8-966a-e2fb1427b875.JPG)

**Comment by JohnnyFFM** [comment]
Hi, it is a known issue, it happens if your number of nonces is not aligned with your sector size. 
This is typically the case if your number of nonces is not a multiple of 8.
Solution 1: Download version v.1.60, it should work
Solution 2: Wait for v.2.0 (weekend), will automatically tackle this issue.
Best, Johnny

**Comment by DefiantMiner** [comment]
Trying 1.6 now, inline, 3 instances.   I'll see how it goes.
